/** Downloadable brand files, generated by scripts/generate-brand-assets.mjs. */

export interface BrandAsset {
  file: string;
  label: string;
  detail: string;
  /** Preview background, since some assets are made for dark and some for light. */
  preview: "dark" | "light";
}

export interface BrandGroup {
  title: string;
  description: string;
  assets: BrandAsset[];
}

export const BRAND_GROUPS: BrandGroup[] = [
  {
    title: "Full logo",
    description:
      "Mark and wordmark together. The default choice wherever there is room for it.",
    assets: [
      {
        file: "payreckon-logo-dark.svg",
        label: "SVG — for dark backgrounds",
        detail: "Vector · scales to any size",
        preview: "dark",
      },
      {
        file: "payreckon-logo-light.svg",
        label: "SVG — for light backgrounds",
        detail: "Vector · scales to any size",
        preview: "light",
      },
      {
        file: "payreckon-logo-dark-4096.png",
        label: "PNG — dark backgrounds",
        detail: "4096px wide · transparent",
        preview: "dark",
      },
      {
        file: "payreckon-logo-light-4096.png",
        label: "PNG — light backgrounds",
        detail: "4096px wide · transparent",
        preview: "light",
      },
      {
        file: "payreckon-logo-dark-2048.png",
        label: "PNG — dark, medium",
        detail: "2048px wide · transparent",
        preview: "dark",
      },
      {
        file: "payreckon-logo-light-2048.png",
        label: "PNG — light, medium",
        detail: "2048px wide · transparent",
        preview: "light",
      },
    ],
  },
  {
    title: "Icon",
    description:
      "The mark on its own — app icons, favicons, social avatars, and anywhere the full logo would be too small to read.",
    assets: [
      {
        file: "payreckon-mark.svg",
        label: "SVG — rounded",
        detail: "Vector · works on any background",
        preview: "light",
      },
      {
        file: "payreckon-mark-square.svg",
        label: "SVG — square",
        detail: "Vector · for platforms that apply their own mask",
        preview: "light",
      },
      {
        file: "payreckon-mark-2048.png",
        label: "PNG — 2048px",
        detail: "Transparent corners",
        preview: "light",
      },
      {
        file: "payreckon-mark-1024.png",
        label: "PNG — 1024px",
        detail: "Transparent corners",
        preview: "light",
      },
      {
        file: "payreckon-mark-512.png",
        label: "PNG — 512px",
        detail: "App icon size",
        preview: "light",
      },
      {
        file: "payreckon-mark-256.png",
        label: "PNG — 256px",
        detail: "Small icon size",
        preview: "light",
      },
    ],
  },
  {
    title: "Wordmark",
    description:
      "Type only, for places that already carry the icon — letterheads, invoice footers, email signatures.",
    assets: [
      {
        file: "payreckon-wordmark-dark.svg",
        label: "SVG — dark backgrounds",
        detail: "Vector",
        preview: "dark",
      },
      {
        file: "payreckon-wordmark-light.svg",
        label: "SVG — light backgrounds",
        detail: "Vector",
        preview: "light",
      },
      {
        file: "payreckon-wordmark-dark-2048.png",
        label: "PNG — dark backgrounds",
        detail: "2048px wide · transparent",
        preview: "dark",
      },
      {
        file: "payreckon-wordmark-light-2048.png",
        label: "PNG — light backgrounds",
        detail: "2048px wide · transparent",
        preview: "light",
      },
    ],
  },
];

export const BRAND_COLOURS = [
  {
    name: "Gold",
    hex: "#C9A227",
    use: "The brand gold. Fills the logo tile and other large shapes",
  },
  {
    name: "Deep gold",
    hex: "#8A6D1A",
    use: "Gold type, links and icons — the brand gold is too light to read",
  },
  { name: "Ink", hex: "#14140D", use: "Body text, and the bars inside the icon" },
  { name: "Cream", hex: "#FAF8F1", use: "Page background" },
  { name: "Surface", hex: "#FFFFFF", use: "Panels and cards" },
  { name: "Muted", hex: "#6D6B58", use: "Secondary body text" },
];
